[package]
name = "eveicongenerator"
version = "1.1.0"
edition = "2024"
publish = false
repository = "https://github.com/SentientTurtle/EVE-3rd-party-dev-tools"

[dependencies]
evesharedcache = { path = "../evesharedcache" }
evestaticdata = { path = "../evestaticdata", features = ["sde_update", "sde_load"] }
zip = "8.6.0"
image = "0.25.10"
image-blend = "0.1.7"
clap = "4.6.6"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
chrono = "0.4.45"
# Intentionally not the RustCrypto one. We don't need all the additional cruft RustCrypto adds.
md5 = "0.8.1"
fs-err = "3.3.1"