name: generate-icons.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '42 10,15 * * *'
      timezone: 'UTC'

permissions:
  contents: write

jobs:
  build-number:
    name: Get build number
    runs-on: ubuntu-latest

    outputs:
      build-number: ${{ steps.get-build-number.outputs.build-number }}
      new-tag: ${{ steps.check-tag.outputs.new-tag }}

    steps:
      - name: Get build number
        id: get-build-number
        run: |
          if [ -n "${{ github.event.inputs.build-number }}" ]; then
            BUILD_NUMBER=${{ github.event.inputs.build-number }}
          else
            BUILD_NUMBER=$(curl -s https://developers.eveonline.com/static-data/tranquility/latest.jsonl | jq -r '.buildNumber')
          fi
  
          echo "Build number: ${BUILD_NUMBER}"
          echo "build-number=${BUILD_NUMBER}" >> $GITHUB_OUTPUT

      - name: Check for existing tag
        id: check-tag
        run: |
          TAG_NAME="icons-${{ steps.get-build-number.outputs.build-number }}"
          REF_NAME=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/${TAG_NAME} | jq -r '.ref')
  
          echo "Tag name: ${TAG_NAME}"
          echo "Ref name: ${REF_NAME}"
  
          if [ -n "${REF_NAME}" ] && [ "${REF_NAME}" != "null" ]; then
            echo "Tag ${TAG_NAME} already exists"
  
            echo "new-tag=false" >> $GITHUB_OUTPUT
            exit 0
          fi
  
          echo "new-tag=true" >> $GITHUB_OUTPUT

  build-icons:
    name: "Build icon outputs"
    runs-on: ubuntu-latest

    needs: [build-number]
    if: needs.build-number.outputs.new-tag == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./eveicongenerator/target
          key: cargo-${{ hashFiles('./evestaticdata/Cargo.lock','./eveicongenerator/Cargo.lock') }}
          restore-keys: |
            cargo
      - name: Cargo Build
        working-directory: ./eveicongenerator
        run: cargo build --release  # Spending longer on compilation is generally worthwhile, as image processing in the debug build is quite slow
      - name: SharedCache cache
        uses: actions/cache@v5
        with:
          path: ./eveicongenerator/cache
          key: SharedCache-${{needs.build-number.outputs.build-number}}
          restore-keys: |
            SharedCache
      - name: Icon cache
        uses: actions/cache@v5
        with:
          path: ./eveicongenerator/icons
          key: IconCache-${{needs.build-number.outputs.build-number}}
          restore-keys: |
            IconCache
      - name: Generate Icons (Accurate)
        working-directory: ./eveicongenerator
        run: cargo run --release --package eveicongenerator --bin eveicongenerator -- -l ./log.txt --user_agent "Github Actions on behalf of ${{ github.repository }}" --no_purge  multi --iec "./Image Export Collection.zip" --service_bundle "./Service Bundle.zip" --aux_shiptree "./Shiptree.zip" --utility_icons "./Utility Icons.zip"
      - name: Generate Icons (Old)
        working-directory: ./eveicongenerator
        run: cargo run --release --package eveicongenerator --bin eveicongenerator -- -l ./log.txt --user_agent "Github Actions on behalf of ${{ github.repository }}" --no_purge --old_overlays  multi --iec "./Image Export Collection - Old Style.zip" --service_bundle "./Service Bundle - Old Style.zip"
      - name: Generate Icons (Bonus)
        working-directory: ./eveicongenerator
        run: cargo run --release --package eveicongenerator --bin eveicongenerator -- -l ./log.txt --user_agent "Github Actions on behalf of ${{ github.repository }}" --no_purge --module_overlays --clone_overlays  multi --iec "./Image Export Collection - Bonus Style.zip" --service_bundle "./Service Bundle - Bonus Style.zip"
      - name: Publish
        uses: softprops/action-gh-release@v3
        with:
          tag_name: icons-${{ needs.build-number.outputs.build-number }}
          fail_on_unmatched_files: true
          working_directory: ./eveicongenerator
          body_path: ./eveicongenerator/README.md
          files: |
            Image Export Collection.zip
            Service Bundle.zip
            Shiptree.zip
            Utility Icons.zip
            Image Export Collection - Old Style.zip
            Service Bundle - Old Style.zip
            Image Export Collection - Bonus Style.zip
            Service Bundle - Bonus Style.zip
